_BASE_: BASE_config.yml
regressor_args:
  Bleach:
    alpha_1: 1.0
    alpha_2: 0.1
    lambda_1: 0.1
    lambda_2: 1.0
  Resolution:
    alpha_1: 1.0
    alpha_2: 0.1
    lambda_1: 0.1
    lambda_2: 1.0
  SNR:
    alpha_1: 1.0
    alpha_2: 0.1
    lambda_1: 0.1
    lambda_2: 1.0
  Squirrel:
    alpha_1: 1.0
    alpha_2: 0.1
    lambda_1: 0.1
    lambda_2: 1.0
  default:
    alpha_1: 1.0e-06
    alpha_2: 1.0e-06
    alpha_init: 0.0625
    compute_score: true
    degree: 3
    fit_intercept: false
    lambda_1: 1.0e-06
    lambda_2: 1.0e-06
    lambda_init: 0.25
    tol: 1.0e-06
regressor_name: sklearn_BayesRidge
