_BASE_:
- BASE_config_LinTSDiag.yml
- BASE_config_rescue.yml
nbre_trials: 1
random_state: 42
param_names:
- p_sted
- p_ex
- lower_threshold
- upper_threshold
- decision_time
x_maxs:
- 350.0e-3
- 2.0e-6
- 50.
- 50.
- 10.0e-6
x_mins:
- 0.
- 0.
- 0.
- 0.
- 0.
regressor_args:
  default:
    n_features: 5
