_BASE_:
- BASE_config_dymin.yml
- BASE_config_contextual-image_LinTSDiag.yml
articulation_opts:
  borders: null
param_names:
- p_sted
- p_ex
- pdt
- threshold_count
- decision_time
random_state: 42
x_maxs:
- 300.0e-3
- 4.0e-6
- 30.0e-6
- 10.
- 5.0e-6
x_mins:
- 0.
- 0.
- 5.0e-6
- 0.
- 0.
regressor_args:
  default:
    n_features: 7
    update_exploration: false