_BASE_:
- BASE_config_abberior-sted.yml
- BASE_config_LinTSDiag.yml
nbre_trials: 1
obj_names:
- Resolution
- Bleach
- SNR
param_names:
- p_sted
- p_ex
- pdt
x_maxs:
- 50.0
- 3.0
- 30.0e-6
x_mins:
- 0.
- 0.
- 1.0e-6
regressor_args:
  default:
    n_features: 3
