_BASE_:
- BASE_config_abberior-dymin.yml
- BASE_config_LinTSDiag.yml
nbre_trials: 1
optim_length: 100
param_names:
- p_ex
- pdt
- ch1_threshold
- ch2_signal_level
- ch2_strength
- ch2_p_sted
- ch3_p_sted
random_state: 42
x_maxs:
- 1.
- 40.0e-6
- 50.
- 75.
- 10.
- 25.
- 50.
x_mins:
- 0.
- 10.0e-6
- 0.
- 0.
- 0.
- 0.
- 0.
regressor_args:
  default:
    n_features: 7
    update_exploration: false
